[package]
name = "toggl_report"
version = "0.1.0"
authors = ["Charlie Tanksley <charlie.tanksley@gmail.com>"]

[dependencies]
csv = { version = "1" }
structopt = { version = "0.2" }
serde = "1"
serde_derive = "1"
